# Generated by Django 3.1.1 on 2021-03-27 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naowaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('husbandname', models.CharField(max_length=255)),
                ('rank', models.CharField(choices=[('Rank', 'Rank'), ('2nd Lt', '2nd Lt'), ('Lt', 'Lt'), ('Capt', 'Capt'), ('Maj', 'Maj'), ('Lt Col', 'Lt Col'), ('Col', 'Col'), ('Brig Gen', 'Brig Gen'), ('Maj Gen', 'Maj Gen')], default='Rank', max_length=255)),
                ('appointment', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=600)),
                ('dob', models.DateField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberss', to='naowaapp.category')),
            ],
        ),
    ]
