# Generated by Django 3.1.1 on 2021-03-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naowaapp', '0003_auto_20210327_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
