# Generated by Django 3.1.1 on 2021-03-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naowaapp', '0004_members_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, max_length=255),
        ),
    ]
