# Generated by Django 3.1.1 on 2021-03-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naowaapp', '0006_members_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='members',
            unique_together={('name', 'slug')},
        ),
    ]
