# Generated by Django 3.1.1 on 2021-03-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naowaapp', '0007_auto_20210330_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={},
        ),
    ]
