# Generated by Django 3.1.1 on 2021-03-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naowaapp', '0009_auto_20210330_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterUniqueTogether(
            name='members',
            unique_together=set(),
        ),
    ]
